import React, { useState } from "react";
import { Mail, Send, CheckCircle2, Copy, Sparkles, X, FileText, GraduationCap, Clock, Code2, User } from "lucide-react";
import { motion } from "motion/react";

interface EmailNotesModalProps {
  onClose: () => void;
  initialRecipient?: string;
  initialSubject?: string;
  initialBody?: string;
}

const PRESET_NOTES = [
  {
    id: "physics-notes",
    category: "🎓 Classroom Study Notes",
    title: "Class 10 Physics: Newton's Laws & Momentum",
    subject: "Study Notes: Newton's Laws of Motion & Momentum",
    body: `ZOYA AI STUDY NOTES - CLASS 10 PHYSICS
--------------------------------------------------
Topic: Newton's Laws of Motion & Momentum

1. First Law (Inertia): An object remains at rest or in uniform motion unless acted upon by an external net force.
2. Second Law (Force Equation): Force = mass * acceleration (F = m * a).
3. Third Law (Action & Reaction): Every action has an equal and opposite reaction.
4. Momentum: Product of mass and velocity (p = m * v). Law of Conservation of Momentum applies in closed systems.

Example Problem:
Force = 20 N, Mass = 5 kg
Acceleration = F / m = 20 / 5 = 4 m/s²

Prepared by Zoya AI Teacher for Hemant.`
  },
  {
    id: "react-notes",
    category: "⚡ Developer Cheatsheet",
    title: "React & VS Code Productivity Snippets",
    subject: "Developer Cheatsheet: React Hooks & Shortcuts",
    body: `ZOYA AI DEVELOPER CHEATSHEET
--------------------------------------------------
Topic: React Hooks & Essential VS Code Shortcuts

Key Hooks:
• useState: Local component state manager
• useEffect: Side-effects, data fetching & subscriptions
• useCallback: Memoized function reference
• useMemo: Memoized expensive calculation

VS Code Shortcuts:
• Multi-Cursor Edit: Alt + Click (Win) / Option + Click (Mac)
• Command Palette: Ctrl + Shift + P
• Duplicate Line: Shift + Alt + DownArrow

Generated by Zoya AI Core.`
  },
  {
    id: "schedule-notes",
    category: "⏰ Timetable & Schedule",
    title: "Daily Study & Work Schedule",
    subject: "Daily Timetable & Study Schedule Reminders",
    body: `ZOYA AI DAILY TIMETABLE
--------------------------------------------------
Owner: Hemant

08:00 AM - Morning Focus & Daily Planning
09:30 AM - Coding & Software Engineering Block
02:00 PM - AI Classroom Study & Physics Review
05:30 PM - Break & Sassy Catchphrase Refresh
08:00 PM - Cyber Security & Web Audit Session

Organized by Zoya Assistant.`
  }
];

export default function EmailNotesModal({
  onClose,
  initialRecipient = "durgeshu49@gmail.com",
  initialSubject = "Zoya AI Study Notes & Reminders",
  initialBody = ""
}: EmailNotesModalProps) {
  const [recipient, setRecipient] = useState(initialRecipient);
  const [subject, setSubject] = useState(initialSubject || PRESET_NOTES[0].subject);
  const [body, setBody] = useState(initialBody || PRESET_NOTES[0].body);
  const [selectedPreset, setSelectedPreset] = useState<string>("physics-notes");
  const [isSending, setIsSending] = useState(false);
  const [sentSuccess, setSentSuccess] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleSelectPreset = (presetId: string) => {
    setSelectedPreset(presetId);
    const found = PRESET_NOTES.find((p) => p.id === presetId);
    if (found) {
      setSubject(found.subject);
      setBody(found.body);
    }
  };

  const handleCopyNotes = () => {
    const fullText = `To: ${recipient}\nSubject: ${subject}\n\n${body}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleOpenEmailClient = () => {
    const mailtoUrl = `mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoUrl, "_blank");
  };

  const handleOpenGmailWeb = () => {
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(recipient)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(gmailUrl, "_blank", "noopener,noreferrer");
  };

  const handleDirectZoyaSend = () => {
    setIsSending(true);
    setTimeout(() => {
      setIsSending(false);
      setSentSuccess(true);
      setTimeout(() => {
        setSentSuccess(false);
      }, 3500);
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-md p-4">
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="w-full max-w-2xl bg-zinc-900 border border-amber-500/30 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
      >
        {/* Header */}
        <div className="px-6 py-4 bg-gradient-to-r from-amber-500/20 via-orange-500/10 to-zinc-900 border-b border-amber-500/20 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-amber-500/20 border border-amber-500/40 text-amber-400">
              <Mail size={22} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                Zoya Email Notes Dispatcher
                <span className="px-2 py-0.5 text-[10px] uppercase font-mono tracking-wider rounded-md bg-amber-500/20 border border-amber-500/30 text-amber-300">
                  Mail Core
                </span>
              </h2>
              <p className="text-xs text-zinc-400">Send classroom lessons, cheatsheets, and reminders straight to email</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-zinc-400 hover:text-white rounded-lg hover:bg-white/10 transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-5 overflow-y-auto flex-1">
          {/* Preset Selector */}
          <div>
            <label className="text-xs font-semibold text-amber-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Sparkles size={14} /> Select Notes Preset
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              {PRESET_NOTES.map((p) => (
                <button
                  key={p.id}
                  onClick={() => handleSelectPreset(p.id)}
                  className={`p-2.5 text-left rounded-xl border text-xs font-medium transition-all ${
                    selectedPreset === p.id
                      ? "bg-amber-500/20 border-amber-500/60 text-white shadow-md shadow-amber-500/10"
                      : "bg-zinc-800/60 border-zinc-700/60 text-zinc-300 hover:bg-zinc-800 hover:border-zinc-600"
                  }`}
                >
                  <p className="text-[10px] text-amber-400 font-mono mb-0.5">{p.category}</p>
                  <p className="line-clamp-1 font-semibold">{p.title}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Email Recipient Input */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-zinc-400 mb-1 flex items-center gap-1">
                <User size={12} className="text-amber-400" /> Recipient Email Address
              </label>
              <input
                type="email"
                value={recipient}
                onChange={(e) => setRecipient(e.target.value)}
                placeholder="e.g. durgeshu49@gmail.com"
                className="w-full bg-zinc-950/80 border border-zinc-700/80 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder-zinc-500 focus:outline-none focus:border-amber-500/60 transition-colors"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-zinc-400 mb-1 flex items-center gap-1">
                <FileText size={12} className="text-amber-400" /> Email Subject
              </label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="Email Subject"
                className="w-full bg-zinc-950/80 border border-zinc-700/80 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder-zinc-500 focus:outline-none focus:border-amber-500/60 transition-colors"
              />
            </div>
          </div>

          {/* Email Body TextArea */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-medium text-zinc-400 flex items-center gap-1">
                <FileText size={12} className="text-amber-400" /> Note Body Content
              </label>
              <button
                onClick={handleCopyNotes}
                className="text-[11px] text-amber-400 hover:text-amber-300 flex items-center gap-1 hover:underline"
              >
                <Copy size={12} /> {copied ? "Copied!" : "Copy Content"}
              </button>
            </div>
            <textarea
              rows={7}
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="w-full bg-zinc-950/90 border border-zinc-700/80 rounded-xl p-3.5 text-xs font-mono text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-amber-500/60 transition-colors leading-relaxed"
            />
          </div>

          {/* Success Banner */}
          {sentSuccess && (
            <motion.div
              initial={{ opacity: 0, y: -5 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-3 bg-emerald-500/15 border border-emerald-500/40 rounded-xl flex items-center gap-2.5 text-emerald-300 text-xs font-medium"
            >
              <CheckCircle2 size={16} className="text-emerald-400 flex-shrink-0" />
              <span>Notes dispatched successfully to <strong>{recipient}</strong> via Zoya Mail Core!</span>
            </motion.div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-zinc-950/90 border-t border-zinc-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={handleOpenGmailWeb}
              className="px-3.5 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-xl text-xs font-medium border border-zinc-700/60 flex items-center gap-1.5 transition-colors"
            >
              <Mail size={14} className="text-red-400" />
              Open in Gmail
            </button>
            <button
              onClick={handleOpenEmailClient}
              className="px-3.5 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-xl text-xs font-medium border border-zinc-700/60 flex items-center gap-1.5 transition-colors"
            >
              <Send size={14} className="text-sky-400" />
              Default Mail App
            </button>
          </div>

          <button
            onClick={handleDirectZoyaSend}
            disabled={isSending || !recipient}
            className="px-5 py-2.5 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 disabled:opacity-50 text-black font-semibold rounded-xl text-xs flex items-center gap-2 shadow-lg shadow-amber-500/20 transition-all"
          >
            {isSending ? (
              <>
                <div className="w-3.5 h-3.5 border-2 border-black/40 border-t-black rounded-full animate-spin" />
                Dispatching Notes...
              </>
            ) : (
              <>
                <Send size={15} />
                Send Notes Now
              </>
            )}
          </button>
        </div>
      </motion.div>
    </div>
  );
}
